// export enum TOKEN_TYPE {
// 	ACCESS_TOKEN_PUBLIC_KEY = "ACCESS_TOKEN_PUBLIC_KEY",
// 	ACCESS_TOKEN_PRIVATE_KEY = "ACCESS_TOKEN_PRIVATE_KEY",
// 	REFRESH_PRIVATE_KEY = "REFRESH_PRIVATE_KEY",
// 	REFRESH_PUBLIC_KEY = "REFRESH_PUBLIC_KEY",
// }
